[2023-12-11 01:33:05,151] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.56:5000 (Press CTRL+C to quit) - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:05,153] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:06,574] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:06] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:06,595] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:06] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:06,719] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:06] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:06,742] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:06] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:06,743] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:06] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:07,820] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:07] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:07,843] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:07] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:07,844] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:07] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:07,845] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:07] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:07,999] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:07] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:33:17,858] WARNING predict() L118  Erro ao adicionar vinho 'None', Não foi possível salvar novo item :/ - call_trace=C:\Lucas\Dev\MVP_Sprint4\engenharia-de-software-main\mvp_sprint4\api\app.py L118 
[2023-12-11 01:33:17,859] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:33:17] "[31m[1mPOST /vinho HTTP/1.1[0m" 400 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:09,296] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.56:5000 (Press CTRL+C to quit) - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:09,299] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:10,583] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:10] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:10,606] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:10] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:10,766] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:10] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:10,769] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:10] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:10,770] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:10] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:11,689] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:11] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:11,707] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:11] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:11,708] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:11] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:11,708] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:11] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:11,853] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:11] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:53:19,708] ERROR log_exception() L1449 Exception on /vinho [POST] - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Lucas\Dev\MVP_Sprint4\engenharia-de-software-main\mvp_sprint4\api\app.py", line 96, in predict
    logger.debug(f"Adicionando vinho de id: '{vinho.name}'")
                                              ^^^^^^^^^^
AttributeError: 'Wines' object has no attribute 'name'
[2023-12-11 01:53:19,712] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:53:19] "[35m[1mPOST /vinho HTTP/1.1[0m" 500 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:55:21,023] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.56:5000 (Press CTRL+C to quit) - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:55:21,024] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:55:22,280] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:55:22] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 01:55:22,299] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 01:55:22] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
