[2023-12-11 02:19:03,498] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.56:5000 (Press CTRL+C to quit) - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:03,500] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:05,777] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:05] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:05,795] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:05] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:05,923] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:05] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:05,937] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:05] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:05,941] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:05] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:06,740] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:06] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:06,761] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:06] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:06,764] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:06] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:06,764] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:06] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:06,907] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:06] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:19:11,128] ERROR log_exception() L1449 Exception on /vinho [POST] - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Lucas\Dev\MVP_Sprint4\engenharia-de-software-main\mvp_sprint4\api\app.py", line 67, in predict
    modelo = Model_Wine.carrega_modelo(ml_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Model_Wine.carrega_modelo() missing 1 required positional argument: 'path'
[2023-12-11 02:19:11,132] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:19:11] "[35m[1mPOST /vinho HTTP/1.1[0m" 500 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:21:43,793] INFO _log() L224   * Detected change in 'C:\\Lucas\\Dev\\MVP_Sprint4\\engenharia-de-software-main\\mvp_sprint4\\api\\model\\modelo.py', reloading - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:21:43,918] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:30,221] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.56:5000 (Press CTRL+C to quit) - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:30,222] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:32,938] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:32] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:32,970] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:32] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:33,085] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:33] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:33,102] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:33] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:33,104] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:33] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:33,936] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:33] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:33,957] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:33] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:33,961] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:33] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:33,961] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:33] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:34,119] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:34] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:22:38,946] WARNING predict() L119  Erro ao adicionar vinho 'Porto', Não foi possível salvar novo item :/ - call_trace=C:\Lucas\Dev\MVP_Sprint4\engenharia-de-software-main\mvp_sprint4\api\app.py L119 
[2023-12-11 02:22:38,947] INFO _log() L224  127.0.0.1 - - [11/Dec/2023 02:22:38] "[31m[1mPOST /vinho HTTP/1.1[0m" 400 - - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:32:05,167] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.56:5000 (Press CTRL+C to quit) - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-12-11 02:32:05,169] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
